# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# Lint lane
lane :lint do
  sh "npm run lint"
end

# Test lane
lane :test do
  sh "npm run test"
end

#Lint and test lane
lane :lint_and_test do
  lint
  test
end

default_platform(:android)

platform :android do
  desc "Build the Android app"
  lane :build_android do
    gradle(
      project_dir: "android/",
      task: "assemble",
      build_type: "Release",
    )
  end

  desc "Deploy the Android app to GitHub releases"
  lane :deploy_android do
    build_number = File.read("../version.txt")
    build_android
    set_github_release(
      api_token: ENV["FASTLANE_ACCESS_TOKEN"],
      repository_name: "wstrzyz/okr-mobile-cicd",
      tag_name: "v#{build_number}",
      name: "okrCICD v#{build_number}",
      description: "Release notes for v#{build_number}",
      upload_assets: [
        "/home/runner/work/okr-mobile-cicd/okr-mobile-cicd/android/app/build/outputs/apk/release/app-release.apk"
      ]
    )
  end
end

# platform :ios do
#   desc "Build the iOS app"
#   lane :build_ios do
#     gym(: "ios/", scheme: "okrMobileCICD", configuration: "Release", export_method: "ad-hoc")
#   end
# end

#   desc "Deploy the iOS app to GitHub releases"
#   lane :deploy_ios do
#     build_number = get_build_number
#     build_ios
#     github_release(
#       api_token: ENV['GITHUB_ACCESS_TOKEN'],
#       owner: "wstrzyz",
#       repo: "wstrzyz/okr-mobile-cicd",
#       tag_name: "v#{build_number}",
#       name: "MyApp v#{build_number}",
#       release_notes: "Release notes for v#{build_number}",
#       draft: false,
#       prerelease: false,
#       assets: [
#         "build/MyApp.ipa",
#         "build/MyApp.app.dSYM.zip"
#       ]
#     )
#   end
# end