# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build the iOS app"
  lane :build_ios do
    gym(scheme: "okrMobileCICD", configuration: "Release", export_method: "ad-hoc")
  end

  desc "Deploy the iOS app to GitHub releases"
  lane :deploy_ios do
    build_number = get_build_number
    build_ios
    github_release(
      api_token: ENV['GITHUB_ACCESS_TOKEN'],
      owner: "wstrzyz",
      repo: "wstrzyz/okr-mobile-cicd",
      tag_name: "v#{build_number}",
      name: "MyApp v#{build_number}",
      release_notes: "Release notes for v#{build_number}",
      draft: false,
      prerelease: false,
      assets: [
        "build/MyApp.ipa",
        "build/MyApp.app.dSYM.zip"
      ]
    )
  end
end