name: lint_test_build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm ci

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.5'

    - name: Install Fastlane
      run: gem install fastlane -N

    - name: Run linting and unit tests
      run: fastlane lint_and_test

    - name: Build Android app
      run: fastlane build_android
